<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>BH.Tool.RoomConfigurator.Client</RootNamespace>
	<PublishTrimmed>false</PublishTrimmed>
	<LinkDuringPublish>false</LinkDuringPublish>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BHoM" Version="6.2.2-alpha" />
    <PackageReference Include="BHoM.Engine" Version="6.2.2-alpha" />
    <PackageReference Include="BHoM.Interop.Data.BuroHappold" Version="6.2.2-alpha" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.20" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="6.9.0" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
	<LinkerRootAssemblies Include="BHoM_Engine" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\charts\" />
    <Folder Include="wwwroot\resources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\RoomConfigurator_Tool_Engine.csproj" />
    <ProjectReference Include="..\oM\RoomConfigurator_Tool_oM.csproj" />
  </ItemGroup>

</Project>
